#!/usr/bin/env ruby

# Router/Dispatch

require './controllers/recipes_controller'
recipes_controller = RecipesController.new

begin
    print "Enter a command (list, show, new, delete, quit): "
    input = gets.chomp.downcase.strip.split(' ')
    command, param = input

    case command
    when 'list', 'l'
        recipes_controller.index
    when 'show', 's'
        recipes_controller.show param
    when 'new', 'n'
        recipes_controller.new
    when 'edit', 'e'
        recipes_controller.edit param
    when 'delete', 'd'
        recipes_controller.destroy param
    end
end until ['quit', 'q'].include? command
