#!/usr/bin/env ruby

# Router/Dispatch

require './controllers/recipes_controller'
recipes_controller = RecipesController.new

begin
    print "Enter a command (new, list, quit): "
    input = gets.chomp.downcase.strip.split(' ')
    command, *params = input

    case command
    when 'list', 'l'
        recipes_controller.index
    when 'show', 's'
        recipes_controller.show *params
    when 'new', 'n'
        recipes_controller.new params
    end

end until ['quit', 'q'].include? command
